### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by malitech** [danielchalmers/Network-Monitor#1]
Hello,
I love this program. Can you please make it show the speed in start menu taskbar?
It can also be added to toolbar to make it show the speed in taskbar.

Thank you!

**Comment by danielchalmers** [comment]
Unfortunately from what I can find "Deskband" toolbars [aren't recommended by Microsoft](https://stackoverflow.com/a/5557765) and [are difficult to implement](https://stackoverflow.com/a/14004209).

[I've added a horizontal layout](https://github.com/danielchalmers/Network-Monitor/releases/tag/2.2.0) that can be placed over the taskbar. Hopefully this can work instead.

**Comment by malitech** [comment]
Thank you!
It shows wrong speed. For example, when I download something, it shows upload 1.8m and download 95m but in real download is 2 mbps and no upload activity. It's strange.

**Comment by danielchalmers** [comment]
It combines the usage data from all network interfaces and includes LAN activity. Could that be why?  
It should show the same thing as the `Network` tab in Resource Monitor.

You can see how it gets usage of the upload [here](https://github.com/danielchalmers/Network-Monitor/blob/d63e1b60ba48ebdbfabeb26b9e61c214642bfee0/Network%20Monitor/Monitors/UploadMonitor.cs#L18) and download [here](https://github.com/danielchalmers/Network-Monitor/blob/d63e1b60ba48ebdbfabeb26b9e61c214642bfee0/Network%20Monitor/Monitors/DownloadMonitor.cs#L18).

**Comment by malitech** [comment]
Oh ok. I think it shows the internet speed and not download and upload speed. For example 20 mbps connection has 2.4 mbps download and upload speed.

I use this now:
http://www.softpedia.com/get/Network-Tools/Bandwidth-Tools/SimpleTrafficMonitor.shtml

I couldn't find any other lightweight tool for measuring bandwidth since years.

**Comment by danielchalmers** [comment]
`20` mega*bits* = `2.5` mega*bytes*.

There's a `Measure in bits` switch that you can turn off if you right click the app. I think that's what you're looking for.

**Comment by malitech** [comment]
Yes, I know. It still doesn't calculate and show it as 2.5 mbps. It shows it as 20 mbps. I have to calculate in mind.

**Comment by danielchalmers** [comment]
That's weird. I'm not sure why it's not working right.
