### ISSUE TITLE
2 flagged this file as malicious

### ISSUE THREAD

**Issue by debpalash** [danielchalmers/Network-Monitor#2]
https://www.virustotal.com/gui/file/1323276d0012a37894fca05a54efa7597dce58617697f109609708d22416d62c

```
MaxSecure

Trojan.Malware.300983.susgen
```

```
Palo Alto Networks

Generic.ml
```

**Comment by danielchalmers** [comment]
2/67 is not bad IMO but do you have suggestions on how to fix the last two?

**Comment by debpalash** [comment]
I personally am not worried about that, i do usual VT checks before running any exe. And thought you might know where false positives are coming from!
